### ISSUE TITLE
Documenting Mixins with Maps

### ISSUE THREAD

**Issue by gisu** [SassDoc/sassdoc#111]
Hi i sitting for my own Framework that need to documented. What is the best Way to document Mixins with Maps - like this:

``` sass
/**
 * Generate the Offset Width for a Colum
 *
 * @param  {map}  $offset - Setup Vars
 *                         :size [number]
 *                           => The required colum size
 *                         :max [number]
 *                           => Max Colums
 *                         :direction [value]
 *                           => The Direction off the Offset (default: left)
 */
@mixin grid-offset($offset) {

  // Setup Default Vars
  $offset: map-merge((
    size: 1,
    max: 12,
    direction: left
  ),$offset);

  // Cleanup Max
  $m: strip-units(map-get($offset,max));
  // Cleanup Colums
  $c: clamp(strip-units(map-get($offset,size)), 0, $m);

  @if map-get($offset,direction) == left {
    margin-left: grid-size($c,$m);
  } @else {
    margin-right: grid-size($c,$m);
  }
}
```

Sassdoc read only the first line (@param) the rest is lost. Is there a possible solution for?

Also i had some Mixins, with Vars that holds posible Values like: 'top', 'left', 'bottom', 'right', 'number' and 'bool'. Is it possible to include linebreaks, so the Description is more readable?

**Comment by ajmueller** [comment]
@gisu and @HugoGiraudel, was a ticket ever opened for this?  I could not find one when browsing the issues.  We've come across a similar situation in our framework.

We [currently use a method similar](https://github.com/isitedesign/Phoenix/blob/master/Assets/src/css/functions/_em.scss#L12-L15) to @gisu for passing in options and merging defaults, but with our move to Sassdoc 2 we are exploring a [slightly different method](https://github.com/isitedesign/Phoenix/blob/feature/sassdoc-2/Assets/src/css/functions/_em.scss) whereby the defaults are defined as a parameter to the function or mixin.  There are a couple downsides to this method:

1. The `$defaults` map really shouldn't be a parameter to the function or mixin, but this is how we can get it documented.  It should be defined within the function, similar to the [common pattern for jQuery plugin development most of us are familiar with](https://mahtonu.wordpress.com/2010/09/20/jquery-plugin-authoring-step-by-step/).
2. If the `$defaults` map has more than a couple keys the display of the Parameters table gets distorted due to the lack of line break support in the Default Value column.

I'm happy to make an issue for this to get the discussion going and I have some ideas for what we're looking for, I just wanted to make sure such an issue hadn't already been created.

**Comment by pascalduez** [comment]
Let's follow the discussion in #386
