### ISSUE TITLE
Infer @access based on name

### ISSUE THREAD

**Issue by kaelig** [SassDoc/sassdoc#340]
In our codebase, all constructs that begin with an underscore are private (as in: not to be used outside of the current module).

```scss
// These are private because their names start with a `_`
function _foo {}
$_foo: bar;
@mixin _foo {}
```

Is this a widely accepted best practice or is it just us? If so, it would be great if we didn't have to mention `/// @access private` before all of these.

**Comment by HugoGiraudel** [comment]
> Is this a widely accepted best practice or is it just us?

It is a widely accepted practice. I am not sure I have ever seen a public item starting with an underscore or an hyphen (since both are strictly equivalent in Sass).

However, we should make sure it can be disabled. Everything assumed by SassDoc should give an option to be disabled if it's doing things wrong. It's the case for autofill for instance.

Anyway, I'm all for it.

**Comment by pascalduez** [comment]
That would fit into an option, something like `privatePrefix: "_"`
Maybe a job for `sassdoc-extras` ?

**Comment by kaelig** [comment]
If you want to be thorough, a regex may be even better.

**Comment by HugoGiraudel** [comment]
> If you want to be thorough, a regex may be even better.

Dito.

**Comment by HugoGiraudel** [comment]
@fweinb Do you think this is something we could do?

**Comment by FWeinb** [comment]
We won't need to implement this in `sassdoc-extras`. I implemented it in #357 using the `privatePrefix` key from the config file.

Do we want to have a default behaviour?

**Comment by HugoGiraudel** [comment]
`^[_-]` would be more correct.

**Comment by FWeinb** [comment]
Done on the PR

**Comment by pascalduez** [comment]
#357 merged.
