### ISSUE TITLE
Issue with `@content` autofill

### ISSUE THREAD

**Issue by pascalduez** [SassDoc/sassdoc#383]
```scss
/// Just a test
/// @content pass in whatever you want
@mixin test($one, $two: null) {}
```
All clear.

```scss
/// Just a test
/// @content pass in whatever you want
@mixin test($one, $two: null) {
  @content;
}
```
Nothing printed.

```scss
/// Just a test
@mixin test($one, $two: null) {
  @content;
}
```
Nothing printed.

```json
{
  "autofill": []
}
```

All clear.

**Comment by HugoGiraudel** [comment]
@FWeinb Any idea?

**Comment by valeriangalliat** [comment]
Just had a look at this issue:

```js
 autofill(item) {
   if (item.context.code.indexOf('@content') > -1) {
     return '';
   }
 },
```

Basically, if there's a `@content` in the code, it's setting `content` to an empty string, regardless an explicit content with a description was set before.

It's a really easy fix, I should really have looked at this before…

```diff
- if (item.context.code.indexOf('@content') > -1) {
+ if (!item.content && item.context.code.indexOf('@content') > -1) {
```

However, there's probably another part of the problem, because when `content` is set to an empty string, it's not displayed. I think it's yet another empty string to boolean conversion problem in the theme.

**Comment by valeriangalliat** [comment]
And that's why we added the `in` filter in default theme (after #323). I'm patching and releasing a new `sassdoc-theme-default` and `sassdoc`.

**Comment by valeriangalliat** [comment]
Fixed with `sassdoc-theme-default@2.3.4` and `sassdoc@2.1.5`.

**Comment by HugoGiraudel** [comment]
You're on fire my friend, terrific!

**Comment by PixelZombie** [comment]
Nice! Thank you
