### ISSUE TITLE
Destination folder relative to config file

### ISSUE THREAD

**Issue by pascalduez** [SassDoc/sassdoc#403]
`sassdoc foo/` 
--> creates a `sassdoc` folder in current working dir.

`sassdoc foo/ -c bar/config.json` 
--> creates a `sassdoc` folder in `bar/`.

@valeriangalliat is that intended somehow ? I find it a bit confusing, plus it's breaking the `grunt-sassdoc` tests, which makes me think it's been introduced by a recent refactor.

**Comment by HugoGiraudel** [comment]
That seems confusing to me.

**Comment by valeriangalliat** [comment]
Oh so this was not a bug in grunt-sassdoc tests. Nope this is not intended.

The bug was introduced with c47dea149771e995b1782fd917e48bec37df48f6. The idea was to make `dest` relative to the configuration file only when defined *from* the configuration file. When `dest` is explicitely given via CLI argument, it is effectively relative to the CWD. The problem is when using the default `dest`.

I'm looking how to fix this.

**Comment by valeriangalliat** [comment]
@pascalduez In grunt-sassdoc, if `dest` was supposed to be relative to CWD, why was `test/docs` ignored in `.gitignore` (instead of `docs`)?

**Comment by pascalduez** [comment]
@valeriangalliat In `grunt-sassdoc` tests I don't use the `dest` option so I assumed all tests to use the CWD (root of the project). In fact, there's only one breaking, the one with a config file.

**Comment by pascalduez** [comment]
> why was test/docs ignored in .gitignore (instead of docs) ?

Well well, I don't remember, that's probably wrong ;-)
